version: '3.5'
services:

  laracastdl:
    container_name: laracastdl
    build:
      context: ./docker/central-webstack-81
      dockerfile: Dockerfile
      args:
        TZ: Europe/Budapest
        WWWUSER: ${UID:-1000}
        WWWGROUP: ${GID:-1000}
        #COMPOSER_VER: 2
    volumes:
      - '.:/var/www/html'
